---
driver:
  name: terraform

provisioner:
  name: terraform

# https://www.rubydoc.info/github/newcontext-oss/kitchen-terraform/Kitchen/Verifier/Terraform

verifier:
  name: terraform
  systems:
    - name: Frontend
      backend: ssh
      user: centos
      show_progress: true
      key_files:
        - /Users/jmiller/.ssh/jmiller
      hosts_output: frontend_server_public_dns
      sudo: true
      attrs_outputs:
        frontend_server_public_ip: frontend_server_public_ip
        backend_server_public_ip: backend_server_public_ip
      # we can also specify which controls run on each node
      controls:
        - role frontend
        - terraform inventory
    - name: Backend
      backend: ssh
      user: centos
      show_progress: true
      key_files:
        - /Users/jmiller/.ssh/jmiller
      hosts_output: backend_server_public_dns
      sudo: true
      attrs_outputs:
        frontend_server_public_ip: frontend_server_public_ip
        backend_server_public_ip: backend_server_public_ip
      controls:
        - role backend
        - terraform inventory

platforms:
  - name: centos

suites:
  - name: default
